// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaolfwlfnrmrpukpkqxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hb2xmd2xmbnJtcnB1a3BrcXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjE3NTEsImV4cCI6MjA3NDIzNzc1MX0.E-F-hAQ8KVhIlj5a66E9v0tYBqwGK_qBmRJJVGHXDBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});